# Example docker-compose.yml file for fullstack Notecz Elysia

version: '3.8'

services:
  app:
    image: ghcr.io/koblizekxd/notecz-elysia:latest
    depends_on:
      - db
    environment:
      TOKEN_EXP: ${TOKEN_EXP}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASS}@db:5432/notecz?schema=public
      POSTGRES_DB: notecz
    networks:
      - app-network
    ports:
      - '3000:3000' # Map your application port

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: notecz
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432' # Expose PostgreSQL

volumes:
  pgdata:

networks:
  app-network: